import { globals } from './globals'
import { writeParagraph } from './writeParagraph';
export const drawMenu = () => {
  if(globals.tagState != 'menu'){
    let containerFluid = document.getElementById('container-fluid');
    let menuRow = document.createElement('div');
    menuRow.id = "menu-row";
    menuRow.classList.add('row', 'background-dark-gray', 'pt-5', 'pb-5');
    let menuContainer = document.createElement('div');
    menuContainer.classList.add('container');
    let innerRow = document.createElement('div');
    innerRow.classList.add('row');
    let titleDiv = document.createElement('div');
    titleDiv.classList.add('col-sm-12');
    let titleTag = document.createElement('h2');
    titleTag.appendChild(document.createTextNode('Take a look at our menu'));
    titleDiv.append(titleTag);
    innerRow.append(titleDiv);

    let menuImage1 = document.createElement('div');
    let menuImage2 = document.createElement('div');
    let menuImage3 = document.createElement('div');
    let menuImage4 = document.createElement('div');
    let menuImage5 = document.createElement('div');
    let menuImage6 = document.createElement('div');
    let menuImage7 = document.createElement('div');
    let menuImage8 = document.createElement('div');
    let menuImage9 = document.createElement('div');
    let menuImagea = document.createElement('div');
    let menuImageb = document.createElement('div');
    let menuImagec = document.createElement('div');
    menuImage1.classList.add('fictional-menu-image');
    menuImage2.classList.add('fictional-menu-image');
    menuImage3.classList.add('fictional-menu-image');
    menuImage4.classList.add('fictional-menu-image');
    menuImage5.classList.add('fictional-menu-image');
    menuImage6.classList.add('fictional-menu-image');
    menuImage7.classList.add('fictional-menu-image');
    menuImage8.classList.add('fictional-menu-image');
    menuImage9.classList.add('fictional-menu-image');
    menuImagea.classList.add('fictional-menu-image');
    menuImageb.classList.add('fictional-menu-image');
    menuImagec.classList.add('fictional-menu-image');

    let unorderedList1 = document.createElement('ul');
    unorderedList1.classList.add('list-group');

    let unorderedList2 = document.createElement('ul');
    unorderedList2.classList.add('list-group');

    let listItem1 = document.createElement('li');
    listItem1.classList.add('list-group-item');
    listItem1.append(menuImage1);
    let p11 = writeParagraph('Cras justo odio');
    p11.classList.add('my-0','ml-3');
    listItem1.append(p11);
    let p12 = writeParagraph('$12');
    p12.classList.add('my-0','ml-auto');
    listItem1.append(p12);
    let listItem2 = document.createElement('li');
    listItem2.classList.add('list-group-item');
    listItem2.append(menuImage2);
    let p21 = writeParagraph('Donec aliquam mi vitae suscipit ornare');
    p21.classList.add('my-0','ml-3');
    listItem2.append(p21);
    let p22 = writeParagraph('$15');
    p22.classList.add('my-0','ml-auto');
    listItem2.append(p22);
    let listItem3 = document.createElement('li');
    listItem3.classList.add('list-group-item');
    listItem3.append(menuImage3);
    let p31 = writeParagraph('Phasellus vitae urna condimentum');
    p31.classList.add('my-0','ml-3');
    listItem3.append(p31);
    let p32 = writeParagraph('$25');
    p32.classList.add('my-0','ml-auto');
    listItem3.append(p32);
    let listItem4 = document.createElement('li');
    listItem4.classList.add('list-group-item');
    listItem4.append(menuImage4);
    let p41 = writeParagraph('Sed imperdiet pulvinar tortor');
    p41.classList.add('my-0','ml-3');
    listItem4.append(p41);
    let p42 = writeParagraph('$11');
    p42.classList.add('my-0','ml-auto');
    listItem4.append(p42);
    let listItem5 = document.createElement('li');
    listItem5.classList.add('list-group-item');
    listItem5.append(menuImage5);
    let p51 = writeParagraph('Curabitur justo nulla');
    p51.classList.add('my-0','ml-3');
    listItem5.append(p51);
    let p52 = writeParagraph('$35');
    p52.classList.add('my-0','ml-auto');
    listItem5.append(p52);
    let listItem6 = document.createElement('li');
    listItem6.classList.add('list-group-item');
    listItem6.append(menuImage6);
    let p61 = writeParagraph('Morbi aliquet aliquet erat eu vestibulum');
    p61.classList.add('my-0','ml-3');
    listItem6.append(p61);
    let p62 = writeParagraph('$16');
    p62.classList.add('my-0','ml-auto');
    listItem6.append(p62);
    unorderedList1.append(listItem1);
    unorderedList1.append(listItem2);
    unorderedList1.append(listItem3);
    unorderedList1.append(listItem4);
    unorderedList1.append(listItem5);
    unorderedList1.append(listItem6);
    let leftColumnDiv = document.createElement('div');
    leftColumnDiv.classList.add('col-sm-12', 'col-lg-6');
    leftColumnDiv.append(unorderedList1);

    let listItem7 = document.createElement('li');
    listItem7.classList.add('list-group-item');
    listItem7.append(menuImage7);
    let p71 = writeParagraph('Duis interdum tempus volutpat');
    p71.classList.add('my-0','ml-3');
    listItem7.append(p71);
    let p72 = writeParagraph('$16');
    p72.classList.add('my-0','ml-auto');
    listItem7.append(p72);
    let listItem8 = document.createElement('li');
    listItem8.classList.add('list-group-item');
    listItem8.append(menuImage8);
    let p81 = writeParagraph('Proin viverra augue eu dui efficitur');
    p81.classList.add('my-0','ml-3');
    listItem8.append(p81);
    let p82 = writeParagraph('$7');
    p82.classList.add('my-0','ml-auto');
    listItem8.append(p82);
    let listItem9 = document.createElement('li');
    listItem9.classList.add('list-group-item');
    listItem9.append(menuImage9);
    let p91 = writeParagraph('Aenean auctor libero ex');
    p91.classList.add('my-0','ml-3');
    listItem9.append(p91);
    let p92 = writeParagraph('$3');
    p92.classList.add('my-0','ml-auto');
    listItem9.append(p92);
    let listItema = document.createElement('li');
    listItema.classList.add('list-group-item');
    listItema.append(menuImagea);
    let pa1 = writeParagraph('Maecenas sed lacinia orci');
    pa1.classList.add('my-0','ml-3');
    listItema.append(pa1);
    let pa2 = writeParagraph('$10');
    pa2.classList.add('my-0','ml-auto');
    listItema.append(pa2);
    let listItemb = document.createElement('li');
    listItemb.classList.add('list-group-item');
    listItemb.append(menuImageb);
    let pb1 = writeParagraph('Duis ultricies feugiat erat ut convallis');
    pb1.classList.add('my-0','ml-3');
    listItemb.append(pb1);
    let pb2 = writeParagraph('$11');
    pb2.classList.add('my-0','ml-auto');
    listItemb.append(pb2);
    let listItemc = document.createElement('li');
    listItemc.classList.add('list-group-item');
    listItemc.append(menuImagec);
    let pc1 = writeParagraph('Vivamus sollicitudin ipsum eget felis scelerisque');
    pc1.classList.add('my-0','ml-3');
    listItemc.append(pc1);
    let pc2 = writeParagraph('$8');
    pc2.classList.add('my-0','ml-auto');
    listItemc.append(pc2);
    unorderedList2.append(listItem7);
    unorderedList2.append(listItem8);
    unorderedList2.append(listItem9);
    unorderedList2.append(listItema);
    unorderedList2.append(listItemb);
    unorderedList2.append(listItemc);
    let rightColumnDiv = document.createElement('div');
    rightColumnDiv.classList.add('col-sm-12','col-lg-6');
    rightColumnDiv.append(unorderedList2);

    innerRow.append(leftColumnDiv);
    innerRow.append(rightColumnDiv);
    menuContainer.append(innerRow);
    menuRow.append(menuContainer);
    containerFluid.append(menuRow);
    globals.tagState = 'menu';
    let homeTag = document.getElementById('home-tag');
    let menuTag = document.getElementById('menu-tag');
    let aboutTag = document.getElementById('about-tag');
    let venuesTag = document.getElementById('venues-tag');
    homeTag.style.backgroundColor = 'transparent';
    menuTag.style.backgroundColor = '#b00';
    aboutTag.style.backgroundColor = 'transparent';
    venuesTag.style.backgroundColor = 'transparent';
    let homeRow = document.getElementById('home-row');
    let aboutRow = document.getElementById('about-row');
    let venuesRow = document.getElementById('venues-row');
    if(homeRow != null)
      homeRow.parentNode.removeChild(homeRow);
    if(aboutRow != null)
      aboutRow.parentNode.removeChild(aboutRow);
    if(venuesRow != null)
      venuesRow.parentNode.removeChild(venuesRow);
  }
};