import globals from './globals';
import writeParagraph from './writeParagraph';
import removeElementAnimation from './removeElementAnimation';

const drawMenu = () => {
  if (globals.tagState !== 'menu') {
    const containerFluid = document.getElementById('container-fluid');
    const menuRow = document.createElement('div');
    menuRow.id = 'menu-row';
    menuRow.classList.add('row', 'background-dark-gray', 'pt-5', 'pb-5');
    const menuContainer = document.createElement('div');
    menuContainer.classList.add('container');
    const innerRow = document.createElement('div');
    innerRow.classList.add('row');
    const titleDiv = document.createElement('div');
    titleDiv.classList.add('col-sm-12');
    const titleTag = document.createElement('h2');
    titleTag.appendChild(document.createTextNode('Take a look at our menu'));
    titleDiv.append(titleTag);
    innerRow.append(titleDiv);

    const menuImage1 = document.createElement('div');
    const menuImage2 = document.createElement('div');
    const menuImage3 = document.createElement('div');
    const menuImage4 = document.createElement('div');
    const menuImage5 = document.createElement('div');
    const menuImage6 = document.createElement('div');
    const menuImage7 = document.createElement('div');
    const menuImage8 = document.createElement('div');
    const menuImage9 = document.createElement('div');
    const menuImagea = document.createElement('div');
    const menuImageb = document.createElement('div');
    const menuImagec = document.createElement('div');
    menuImage1.classList.add('fictional-menu-image');
    menuImage2.classList.add('fictional-menu-image');
    menuImage3.classList.add('fictional-menu-image');
    menuImage4.classList.add('fictional-menu-image');
    menuImage5.classList.add('fictional-menu-image');
    menuImage6.classList.add('fictional-menu-image');
    menuImage7.classList.add('fictional-menu-image');
    menuImage8.classList.add('fictional-menu-image');
    menuImage9.classList.add('fictional-menu-image');
    menuImagea.classList.add('fictional-menu-image');
    menuImageb.classList.add('fictional-menu-image');
    menuImagec.classList.add('fictional-menu-image');

    const unorderedList1 = document.createElement('ul');
    unorderedList1.classList.add('list-group');

    const unorderedList2 = document.createElement('ul');
    unorderedList2.classList.add('list-group');

    const listItem1 = document.createElement('li');
    listItem1.classList.add('list-group-item');
    listItem1.append(menuImage1);
    const p11 = writeParagraph('Cras justo odio');
    p11.classList.add('my-0', 'ml-3');
    listItem1.append(p11);
    const p12 = writeParagraph('$12');
    p12.classList.add('my-0', 'ml-auto');
    listItem1.append(p12);
    const listItem2 = document.createElement('li');
    listItem2.classList.add('list-group-item');
    listItem2.append(menuImage2);
    const p21 = writeParagraph('Donec aliquam mi vitae suscipit ornare');
    p21.classList.add('my-0', 'ml-3');
    listItem2.append(p21);
    const p22 = writeParagraph('$15');
    p22.classList.add('my-0', 'ml-auto');
    listItem2.append(p22);
    const listItem3 = document.createElement('li');
    listItem3.classList.add('list-group-item');
    listItem3.append(menuImage3);
    const p31 = writeParagraph('Phasellus vitae urna condimentum');
    p31.classList.add('my-0', 'ml-3');
    listItem3.append(p31);
    const p32 = writeParagraph('$25');
    p32.classList.add('my-0', 'ml-auto');
    listItem3.append(p32);
    const listItem4 = document.createElement('li');
    listItem4.classList.add('list-group-item');
    listItem4.append(menuImage4);
    const p41 = writeParagraph('Sed imperdiet pulvinar tortor');
    p41.classList.add('my-0', 'ml-3');
    listItem4.append(p41);
    const p42 = writeParagraph('$11');
    p42.classList.add('my-0', 'ml-auto');
    listItem4.append(p42);
    const listItem5 = document.createElement('li');
    listItem5.classList.add('list-group-item');
    listItem5.append(menuImage5);
    const p51 = writeParagraph('Curabitur justo nulla');
    p51.classList.add('my-0', 'ml-3');
    listItem5.append(p51);
    const p52 = writeParagraph('$35');
    p52.classList.add('my-0', 'ml-auto');
    listItem5.append(p52);
    const listItem6 = document.createElement('li');
    listItem6.classList.add('list-group-item');
    listItem6.append(menuImage6);
    const p61 = writeParagraph('Morbi aliquet aliquet erat eu vestibulum');
    p61.classList.add('my-0', 'ml-3');
    listItem6.append(p61);
    const p62 = writeParagraph('$16');
    p62.classList.add('my-0', 'ml-auto');
    listItem6.append(p62);
    unorderedList1.append(listItem1);
    unorderedList1.append(listItem2);
    unorderedList1.append(listItem3);
    unorderedList1.append(listItem4);
    unorderedList1.append(listItem5);
    unorderedList1.append(listItem6);
    const leftColumnDiv = document.createElement('div');
    leftColumnDiv.classList.add('col-sm-12', 'col-lg-6');
    leftColumnDiv.append(unorderedList1);

    const listItem7 = document.createElement('li');
    listItem7.classList.add('list-group-item');
    listItem7.append(menuImage7);
    const p71 = writeParagraph('Duis interdum tempus volutpat');
    p71.classList.add('my-0', 'ml-3');
    listItem7.append(p71);
    const p72 = writeParagraph('$16');
    p72.classList.add('my-0', 'ml-auto');
    listItem7.append(p72);
    const listItem8 = document.createElement('li');
    listItem8.classList.add('list-group-item');
    listItem8.append(menuImage8);
    const p81 = writeParagraph('Proin viverra augue eu dui efficitur');
    p81.classList.add('my-0', 'ml-3');
    listItem8.append(p81);
    const p82 = writeParagraph('$7');
    p82.classList.add('my-0', 'ml-auto');
    listItem8.append(p82);
    const listItem9 = document.createElement('li');
    listItem9.classList.add('list-group-item');
    listItem9.append(menuImage9);
    const p91 = writeParagraph('Aenean auctor libero ex');
    p91.classList.add('my-0', 'ml-3');
    listItem9.append(p91);
    const p92 = writeParagraph('$3');
    p92.classList.add('my-0', 'ml-auto');
    listItem9.append(p92);
    const listItema = document.createElement('li');
    listItema.classList.add('list-group-item');
    listItema.append(menuImagea);
    const pa1 = writeParagraph('Maecenas sed lacinia orci');
    pa1.classList.add('my-0', 'ml-3');
    listItema.append(pa1);
    const pa2 = writeParagraph('$10');
    pa2.classList.add('my-0', 'ml-auto');
    listItema.append(pa2);
    const listItemb = document.createElement('li');
    listItemb.classList.add('list-group-item');
    listItemb.append(menuImageb);
    const pb1 = writeParagraph('Duis ultricies feugiat erat ut convallis');
    pb1.classList.add('my-0', 'ml-3');
    listItemb.append(pb1);
    const pb2 = writeParagraph('$11');
    pb2.classList.add('my-0', 'ml-auto');
    listItemb.append(pb2);
    const listItemc = document.createElement('li');
    listItemc.classList.add('list-group-item');
    listItemc.append(menuImagec);
    const pc1 = writeParagraph('Vivamus sollicitudin ipsum eget felis scelerisque');
    pc1.classList.add('my-0', 'ml-3');
    listItemc.append(pc1);
    const pc2 = writeParagraph('$8');
    pc2.classList.add('my-0', 'ml-auto');
    listItemc.append(pc2);
    unorderedList2.append(listItem7);
    unorderedList2.append(listItem8);
    unorderedList2.append(listItem9);
    unorderedList2.append(listItema);
    unorderedList2.append(listItemb);
    unorderedList2.append(listItemc);
    const rightColumnDiv = document.createElement('div');
    rightColumnDiv.classList.add('col-sm-12', 'col-lg-6');
    rightColumnDiv.append(unorderedList2);

    innerRow.append(leftColumnDiv);
    innerRow.append(rightColumnDiv);
    menuContainer.append(innerRow);
    containerFluid.append(menuRow);
    globals.tagState = 'menu';
    const homeTag = document.getElementById('home-tag');
    const menuTag = document.getElementById('menu-tag');
    const aboutTag = document.getElementById('about-tag');
    const venuesTag = document.getElementById('venues-tag');
    homeTag.style.backgroundColor = 'transparent';
    menuTag.style.backgroundColor = '#b00';
    aboutTag.style.backgroundColor = 'transparent';
    venuesTag.style.backgroundColor = 'transparent';
    const homeRow = document.getElementById('home-row');
    const aboutRow = document.getElementById('about-row');
    const venuesRow = document.getElementById('venues-row');
    if (homeRow != null) {
      removeElementAnimation(homeRow, menuRow, menuContainer);
    }
    if (aboutRow != null) {
      removeElementAnimation(aboutRow, menuRow, menuContainer);
    }
    if (venuesRow != null) {
      removeElementAnimation(venuesRow, menuRow, menuContainer);
    }
  }
};

export { drawMenu as default };